name: Galaxies Reborn - Continuous Integration for src repo

on:
  pull_request:
    types:
      - opened
      - sychronize
      
jobs:
  compile-src:
    runs-on: ubuntu-latest
    container: cekisswg/swg-vm3.01-i386:latest
    steps:
      - name: Clone repository
        run: |
          cd /home/swg/swg-main
          git clone https://github.com/Galaxies-Reborn/src.git
          cd src
          ant build_src

          
